<a href="https://colab.research.google.com/github/darshanjoshi16/MachineLearningPracticals/blob/main/Practical%202(NumPy%20Tutorial)/ML_Practical_2_NumPy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy Tutorial**

# Basics of NumPy 

In [2]:


#Create an alias with the as keyword while importing:
import numpy as np

#Creating an array using the array() function:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr)

print(type(arr)) #tells us the type of the object passed to it

#Use a tuple to create a NumPy array:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[10 20 30 40 50]
<class 'numpy.ndarray'>
[1 2 3 4 5]


# Dimensions in Array

**Create a 0-D array with value 42**

In [3]:
import numpy as np
arr = np.array(42)
print(arr)

42


**Create a 1-D array containing the values 1,2,3,4,5** 

In [4]:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


**Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:**

In [5]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


**Create a 3-D array with 2 arrays both containing two arrays with the
values 1,2,3 and 4,5,6**

In [6]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


**Create an array with 5 dimensions and verify that it has 5 dimensions:**

In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# NumPy Array Indexing

**Get the first element from the following array:**

In [8]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


**Access the 2nd element on 1st dim:**

In [9]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


**Access the third element of the second array of the first array:**

In [10]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


**Use negative indexing to access an array from the end.**

In [11]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# Slicing arrays

**Slice elements from index 1 to index 5 from the following array:**

In [12]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


**Slice from the index 3 from the end to index 1 from the end:**

In [13]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


**(1).Return every other element from index 1 to index 5:**

**(2).From the second element, slice elements from index 1 to index 4 (not
included):**

In [14]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[2 4]
[7 8 9]


**Make a copy, change the original array, and display both arrays:**

In [15]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


**Make a view, change the original array, and display both arrays:**

In [19]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


# Shape of an Array

**Print the shape of a 2-D array:**

In [20]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


**Create an array with 5 dimensions using ndmin using a vector with values
1,2,3,4 and verify that last dimension has value 4:**

In [21]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# Reshaping arrays

**Convert the following 1-D array with 12 elements into a 2-D array.
The outermost dimension will have 4 arrays, each with 3 elements:**

In [22]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Flattening the arrays

**Convert the 2D array into a 1D array:**

In [23]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


# Iterating Arrays

**Iterate on the elements of the following 1-D array:**

In [24]:
import numpy as np
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3


**Iterate on each scalar element of the 2-D array:**

In [25]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


**Iterate through the following 3-D array:**

In [26]:
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


# Joining NumPy Arrays

**Join two arrays**

In [27]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


**Join two 2-D arrays along rows (axis=1):**

In [28]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


# Splitting NumPy Arrays

**Split the array in 3 parts:**

In [29]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


**Split the 2-D array into three 2-D arrays.**

In [30]:
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


**Split the 2-D array into three 2-D arrays along rows.**

In [31]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14,
15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# Searching Arrays

**Find the indexes where the value is 4:**

In [32]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


**Find the indexes where the value 7 should be inserted using SearchSorted():**

In [33]:
import numpy as np
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


**Find the indexes where the value 7 should be inserted, starting from the right:**

In [34]:
import numpy as np
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)

2


# NumPy Sorting Arrays

**Sort the array:**

In [35]:
import numpy as np
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


**Sort the array alphabetically:**

In [36]:
import numpy as np
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


**Sort a 2-D array:**

In [37]:
import numpy as np
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# Filtering Arrays

**Create an array from the elements on index 0 and 2:**

In [38]:
import numpy as np
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]

newarr = arr[x]
print(newarr)

[41 43]


**Create a filter array that will return only values higher than 42:**

In [39]:
import numpy as np
arr = np.array([41, 42, 43, 44])
# Create an empty list
filter_arr = []
# go through each element in arr
for element in arr:
# if the element is higher than 42, set the value to True, otherwise False:

  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

 

[False, False, True, True]
[43 44]


**Create a filter array that will return only values higher than 42 (Using filter from Directly array)**

In [40]:
import numpy as np
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


**Create a filter array that will return only even elements from the original array**

In [41]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
